"""Check print-critical geometry and CMS-to-gallery contracts through build outputs."""
import copy
import importlib.util
from html.parser import HTMLParser
import json
from pathlib import Path
import sys
import unittest
from urllib.parse import unquote, urlparse

import trimesh

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / 'scripts'))
from build_openscad import configurations, parameters, source_text
from config_utils import load_config, output_stem
from generate_openscad_site import detail_page


class Links(HTMLParser):
    def __init__(self):
        super().__init__()
        self.paths = []
    def handle_starttag(self, tag, attrs):
        for key, value in attrs:
            if key in ('href', 'src') and value:
                self.paths.append(value)


class OpenSCADBuildTests(unittest.TestCase):
    def test_all_configurations_are_closed_printable_solids(self):
        entries = list(configurations())
        self.assertGreater(len(entries), 0)
        for path, kind in entries:
            with self.subTest(path=path.name):
                config = load_config(path)
                artifact = ROOT / 'outputs' / 'openscad' / (output_stem(path, config) + '.stl')
                mesh = trimesh.load(artifact, force='mesh')
                self.assertTrue(mesh.is_watertight)
                self.assertTrue(mesh.is_winding_consistent)
                self.assertGreater(mesh.volume, 0)
                components = mesh.split(only_watertight=False)
                self.assertEqual(len(components), 2 if kind == 'pen' else 1)
                values = parameters(config, kind)
                expected_height = (values['cylinder_height'] + values['frustum_height'] if kind == 'pen'
                                   else values['back_height_in'] * 25.4)
                self.assertAlmostEqual(mesh.extents[2], expected_height, delta=0.015)
                if kind == 'c_bracket':
                    self.assertAlmostEqual(mesh.extents[0], values['width_in'] * 25.4, delta=0.015)
                    self.assertAlmostEqual(mesh.extents[1], values['length_in'] * 25.4, delta=0.015)

    def test_mesh_matches_cadquery_dimensions_and_rounded_volume(self):
        from cad.engine import build
        for path, kind in configurations():
            with self.subTest(path=path.name):
                config = load_config(path)
                if kind == 'pen':
                    original = build(config)
                else:
                    spec = importlib.util.spec_from_file_location('original_bracket', path.parent / 'model.py')
                    module = importlib.util.module_from_spec(spec)
                    spec.loader.exec_module(module)
                    original = module.build(config.get('model', {}))
                solid = original.val()
                bounds = solid.BoundingBox()
                expected = [bounds.xlen, bounds.ylen, bounds.zlen]
                mesh = trimesh.load(ROOT / 'outputs/openscad' / (output_stem(path, config) + '.stl'), force='mesh')
                for actual, dimension in zip(mesh.extents, expected):
                    self.assertAlmostEqual(actual, dimension, delta=0.015)
                self.assertLess(abs(mesh.volume - solid.Volume()) / solid.Volume(), 0.002)

    def test_portable_sources_and_downloads_match_every_config(self):
        data = json.loads((ROOT / 'site/openscad/data.json').read_text())['pens']
        self.assertEqual(len(data), len(list(configurations())))
        for item in data:
            self.assertEqual(set(item['downloads']), {'stl', 'scad'})
            for extension, path in item['downloads'].items():
                self.assertIsNotNone(path)
                self.assertTrue((ROOT / path).is_file())
                if extension == 'scad':
                    text = (ROOT / path).read_text()
                    self.assertNotIn('include <', text)
                    self.assertNotIn('use <', text)

    def test_gallery_local_resources_resolve_under_published_layout(self):
        # Published site puts assets/ and outputs/ next to the site content.
        for page in (ROOT / 'site/openscad').rglob('*.html'):
            parser = Links()
            parser.feed(page.read_text())
            for link in parser.paths:
                parsed = urlparse(link)
                if parsed.scheme or link.startswith('#'):
                    continue
                target = (page.parent / unquote(parsed.path)).resolve()
                # CadQuery counterparts are generated by the existing deploy pipeline.
                if target.parent == ROOT / 'site/pens':
                    expected = {p.stem if kind == 'pen' else p.parent.name for p, kind in configurations()}
                    self.assertIn(target.stem, expected)
                    continue
                if not target.exists() and target.is_relative_to(ROOT / 'site'):
                    target = ROOT / target.relative_to(ROOT / 'site')
                self.assertTrue(target.exists(), f'{page.name}: {link}')

    def test_invalid_dimensions_cannot_produce_a_download(self):
        path, kind = next(configurations())
        config = load_config(path)
        for key, value in [('cylinder_height', -1), ('top_hole_height', 999),
                           ('top_hole_diameter', float('nan')), ('frustum_height', True)]:
            bad = copy.deepcopy(config)
            bad['nose_cone'][key] = value
            with self.subTest(key=key), self.assertRaises(ValueError):
                source_text(bad, kind)
        with self.assertRaises(ValueError):
            source_text({'model': {}}, 'unknown_model')

    def test_config_text_is_not_interpreted_as_page_markup(self):
        item = {'slug': 'example', 'id': 'example', 'title': '<script>alert(1)</script>',
                'description': '<img src=x onerror=alert(1)>', 'parameters': {},
                'images': [], 'downloads': {'stl': None, 'scad': None}}
        page = detail_page(item)
        self.assertNotIn('<script>alert(1)</script>', page)
        self.assertNotIn('<img src=x onerror', page)
        self.assertIn('&lt;script&gt;', page)


if __name__ == '__main__':
    unittest.main()
