# Fast settings for 0.4mm nozzle
nozzle_diameter = 0.4
filament_diameter = 1.75
extrusion_multiplier = 1.0
layer_height = 0.20
first_layer_height = 0.20
perimeters = 2
top_solid_layers = 5
bottom_solid_layers = 3
fill_density = 15%
fill_pattern = grid
infill_speed = 150
perimeter_speed = 100
external_perimeter_speed = 80
first_layer_speed = 30
slowdown_below_layer_time = 8
min_print_speed = 10
fan_always_on = 1
min_fan_speed = 100
max_fan_speed = 100
max_volumetric_speed = 12
travel_speed = 200
max_acceleration_x = 10000
max_acceleration_y = 10000
max_acceleration_z = 500
max_acceleration_e = 5000
gcode_flavor = marlin
support_material = 0
