# Fast settings for 0.2mm nozzle
layer_height = 0.15
first_layer_height = 0.15
perimeters = 2
top_solid_layers = 4
bottom_solid_layers = 3
fill_density = 10%
fill_pattern = grid
infill_speed = 100
perimeter_speed = 60
external_perimeter_speed = 40
support_material = 0
